version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: randoquest_db
    restart: always
    environment:
      MYSQL_DATABASE: randoquest_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - randoquest_net

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    container_name: randoquest_app
    restart: always
    environment:
      - DB_HOST=db_service
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=randoquest_db
      - APP_PORT=3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # Mencegah node_modules lokal menimpa di dalam container
    depends_on:
      - db_service
    networks:
      - randoquest_net

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: randoquest_nginx
    restart: always
    ports:
      - "2581:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - randoquest_net

#--- VOLUMES AND NETWORKS ---
volumes:
  mysql_data:


networks:
  randoquest_net:
    driver: bridge
